data1 <- read_excel("donnees/FREQUENTATION_export_2005-2013.xlsx", 
                   sheet = 1)
library(dplyr)
glimpse(data1)

table(data1$AMP)
length(unique(data1$numSortie))
table(data1$numSortie)
table(data1$nbMoyen)
table(data1$periodEchant)
table(data1$annee)
table(data1$mois)
table(data1$jour)
table(data1$saison)
table(data1$typeJ)
table(data1$heure)
length(unique(data1$heure))
table(data1$meteo)
table(data1$nebulosite)
table(data1$directionVent)
length(unique(data1$directionVent))
table(data1$forceVent)
table(data1$etatMer)
table(data1$lune)
table(data1$zone)
length(unique(data1$zone))
table(data1$zonagePAMPA)
table(data1$groupe)
length(unique(data1$groupe))
table(data1$typeBat)
table(data1$tailleBat)
table(data1$immat)
length(unique(data1$immat))
sum(data1$immat == "inconnu")
table(data1$nbPers)
table(data1$nbLigne)
table(data11$mouillage)
table(data1$natureFond)
table(data1$latitude == "NA")
length(unique(data1$latitude))
table(data1$longitude == "NA")
length(unique(data1$longitude))
table(data11$act1)
table(data11$categAct1)
table(data1$act2)
table(data1$categAct2)
table(data1$questInfo)
length(unique(data1$questInfo))
table(data1$sens1)
table(data1$sens2)
table(data1$doubleSortie)


